In [13]:
#1
import numpy as np

print(np.__version__)

2.1.3


In [16]:
import pandas as pd

df = pd.read_csv("/content/it_services_tickets_cleaned.csv", low_memory=False)

In [26]:
#2
hours = df['hours_logged'].to_numpy()
print(hours)

[  nan  1.34  7.   ... 47.    2.     nan]


In [27]:
#3
print("Shape: ", hours.shape)
print("Size: ", hours.size)
print("Dimension: ", hours.dtype)

Shape:  (48123,)
Size:  48123
Dimension:  float64


In [31]:
#4
print(np.arange(1,51))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [33]:
#5
print(np.linspace(0,100,10))

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [37]:
#6
print(np.zeros(10))
print(np.ones(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [40]:
#7
np.random.seed(42)

print(np.random.random((3, 3)))

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [46]:
#8
hours_rate = np.array([
    hours,
    df["billing_rate_(usd)"].to_numpy()
])

print(hours_rate)

[[  nan   nan]
 [ 1.34 33.15]
 [ 7.   48.1 ]
 ...
 [47.     nan]
 [ 2.     nan]
 [  nan 89.02]]


In [48]:
#9
print(hours_rate.ndim)

2


In [50]:
#10
print(hours[:5])

[  nan  1.34  7.   34.63 12.76]


In [51]:
#11
print(hours[:5])

[  nan  1.34  7.   34.63 12.76]


In [53]:
#12
print(hours[:20:2])

[   nan   7.    12.76    nan   1.66    nan  11.63  28.     0.59 253.85]


In [54]:
#13
print(hours[:20:2])

[   nan   7.    12.76    nan   1.66    nan  11.63  28.     0.59 253.85]


In [55]:
#14
print(np.sum(hours))

nan


In [56]:
#15
print("Mean:", np.nanmean(hours))
print("Minimum:", np.nanmin(hours))
print("Maximum:", np.nanmax(hours))

Mean: 63.16764267784735
Minimum: -12.5
Maximum: 9888.01


In [58]:
#16
print(np.nanstd(hours))

493.3142529221527


In [60]:
#17
print(np.nanmedian(hours))

13.1


In [61]:
#18
print(np.isnan(hours).sum())

11870


In [62]:
#19
print(np.nanmean(hours))

63.16764267784735


In [63]:
#20
hours_no_missing = np.nan_to_num(hours, nan=0)

print(hours_no_missing)

[ 0.    1.34  7.   ... 47.    2.    0.  ]


In [64]:
#21
print(np.sum(hours > 100))

1588


In [65]:
#22
print(hours[hours > 100])

[ 253.85  128.   1900.66 ...  562.22  141.9   137.56]


In [66]:
#23
print(hours[hours > 100])

[ 253.85  128.   1900.66 ...  562.22  141.9   137.56]


In [67]:
#24
print(np.sum(hours < 0))

136


In [68]:
#25
hours_non_negative = hours.copy()

hours_non_negative[hours_non_negative < 0] = 0

print(hours_non_negative)

[  nan  1.34  7.   ... 47.    2.     nan]


In [69]:
#26
sorted_hours = np.sort(hours)

print(sorted_hours)

[-12.5 -12.5 -12.5 ...   nan   nan   nan]


In [70]:
#27
print(np.nanargmax(hours))

10041


In [71]:
#28
print(np.nanargmin(hours))

606


In [72]:
#29
print(np.sort(hours[~np.isnan(hours)])[-5:])

[8760.   8760.   8760.   9888.01 9888.01]


In [73]:
#30
rounded_hours = np.round(hours, 1)

print(rounded_hours)

[ nan  1.3  7.  ... 47.   2.   nan]


In [74]:
#31
rounded_hours = np.round(hours, 1)

print(rounded_hours)

[ nan  1.3  7.  ... 47.   2.   nan]


In [75]:
#32
hours_plus_10 = hours + 10

print(hours_plus_10)

[  nan 11.34 17.   ... 57.   12.     nan]


In [76]:
#33
billing_rate = df["billing_rate_(usd)"].to_numpy()

revenue = hours * billing_rate

print(revenue)

[    nan  44.421 336.7   ...     nan     nan     nan]


In [77]:
#34
print(len(hours) == len(billing_rate))

True


In [78]:
#35
speed = np.where(hours > 24, "slow", "fast")

print(speed)

['fast' 'fast' 'fast' ... 'slow' 'fast' 'fast']


In [82]:
#36
priority = df["priority"].dropna().to_numpy()
unique_priorities = np.unique(priority)
print(unique_priorities)

[' ' '--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High' 'LOW'
 'Low' 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4' 'PRIORITY'
 'high' 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3' 'p4']


In [83]:
#37
values, counts = np.unique(priority, return_counts=True)

print(values)
print(counts)

[' ' '--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High' 'LOW'
 'Low' 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4' 'PRIORITY'
 'high' 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3' 'p4']
[  95  107 1931 1966 1934 1919   85 1993 2000 1950 2003 1945 1840 1949
 1941 1891 1969 1907 1950 1880    1 1971 1950 2023  125  130 1934 1898
 1988 1909]


In [84]:
#38
first_100 = hours[:100]

array_10x10 = first_100.reshape(10, 10)

print(array_10x10)

[[         nan  1.34000e+00  7.00000e+00  3.46300e+01  1.27600e+01
   1.53000e+01          nan  9.00000e+00  1.66000e+00          nan]
 [         nan  1.44000e+00  1.16300e+01  7.23100e+01  2.80000e+01
   1.01600e+01  5.90000e-01  7.00000e+00  2.53850e+02  4.20000e+00]
 [ 5.08100e+01  8.01000e+00  6.79400e+01          nan  3.27100e+01
           nan  6.91000e+00  3.08400e+01  3.51000e+00  4.34000e+00]
 [ 1.80000e+01  3.14400e+01  3.42000e+00  2.44600e+01          nan
   1.30000e+01  3.00200e+01  1.15100e+01  6.30200e+01  1.03000e+00]
 [         nan  3.92000e+00  2.02200e+01  2.41500e+01  8.40000e+01
           nan  2.70000e+01          nan  4.00000e+00  2.76000e+00]
 [ 1.12600e+01  2.40000e+01  5.26000e+00  1.40000e+01  5.00000e+00
   1.14100e+01          nan  1.80000e+01  1.28000e+02  1.54000e+01]
 [ 1.90066e+03  4.00000e+00  3.00000e+00  9.00000e+00  1.33350e+02
           nan  4.00000e+00          nan  2.00000e+00          nan]
 [ 2.05100e+01  1.13300e+01  5.99100e+01  1.00000e+00  

In [85]:
#39
transposed = array_10x10.T

print(transposed)

[[         nan          nan  5.08100e+01  1.80000e+01          nan
   1.12600e+01  1.90066e+03  2.05100e+01  1.91700e+01  1.30000e+01]
 [ 1.34000e+00  1.44000e+00  8.01000e+00  3.14400e+01  3.92000e+00
   2.40000e+01  4.00000e+00  1.13300e+01  1.78600e+01  1.09100e+01]
 [ 7.00000e+00  1.16300e+01  6.79400e+01  3.42000e+00  2.02200e+01
   5.26000e+00  3.00000e+00  5.99100e+01  9.21000e+00  8.00000e+00]
 [ 3.46300e+01  7.23100e+01          nan  2.44600e+01  2.41500e+01
   1.40000e+01  9.00000e+00  1.00000e+00  5.40000e+01  3.81000e+00]
 [ 1.27600e+01  2.80000e+01  3.27100e+01          nan  8.40000e+01
   5.00000e+00  1.33350e+02  2.29700e+01          nan  3.73680e+02]
 [ 1.53000e+01  1.01600e+01          nan  1.30000e+01          nan
   1.14100e+01          nan -1.20000e+01  2.00000e+01  1.13800e+01]
 [         nan  5.90000e-01  6.91000e+00  3.00200e+01  2.70000e+01
           nan  4.00000e+00          nan  6.00000e+00  3.36700e+01]
 [ 9.00000e+00  7.00000e+00  3.08400e+01  1.15100e+01  

In [86]:
#40
flattened = array_10x10.flatten()

print(flattened)

[         nan  1.34000e+00  7.00000e+00  3.46300e+01  1.27600e+01
  1.53000e+01          nan  9.00000e+00  1.66000e+00          nan
          nan  1.44000e+00  1.16300e+01  7.23100e+01  2.80000e+01
  1.01600e+01  5.90000e-01  7.00000e+00  2.53850e+02  4.20000e+00
  5.08100e+01  8.01000e+00  6.79400e+01          nan  3.27100e+01
          nan  6.91000e+00  3.08400e+01  3.51000e+00  4.34000e+00
  1.80000e+01  3.14400e+01  3.42000e+00  2.44600e+01          nan
  1.30000e+01  3.00200e+01  1.15100e+01  6.30200e+01  1.03000e+00
          nan  3.92000e+00  2.02200e+01  2.41500e+01  8.40000e+01
          nan  2.70000e+01          nan  4.00000e+00  2.76000e+00
  1.12600e+01  2.40000e+01  5.26000e+00  1.40000e+01  5.00000e+00
  1.14100e+01          nan  1.80000e+01  1.28000e+02  1.54000e+01
  1.90066e+03  4.00000e+00  3.00000e+00  9.00000e+00  1.33350e+02
          nan  4.00000e+00          nan  2.00000e+00          nan
  2.05100e+01  1.13300e+01  5.99100e+01  1.00000e+00  2.29700e+01
 -1.20000e

In [87]:
#41
array1 = hours[:10]
array2 = hours[10:20]

joined = np.concatenate((array1, array2))

print(joined)

[   nan   1.34   7.    34.63  12.76  15.3     nan   9.     1.66    nan
    nan   1.44  11.63  72.31  28.    10.16   0.59   7.   253.85   4.2 ]


In [88]:
#42
first_100 = hours[:100]

parts = np.array_split(first_100, 5)

for part in parts:
    print(part)

[   nan   1.34   7.    34.63  12.76  15.3     nan   9.     1.66    nan
    nan   1.44  11.63  72.31  28.    10.16   0.59   7.   253.85   4.2 ]
[50.81  8.01 67.94   nan 32.71   nan  6.91 30.84  3.51  4.34 18.   31.44
  3.42 24.46   nan 13.   30.02 11.51 63.02  1.03]
[   nan   3.92  20.22  24.15  84.      nan  27.      nan   4.     2.76
  11.26  24.     5.26  14.     5.    11.41    nan  18.   128.    15.4 ]
[ 1.90066e+03  4.00000e+00  3.00000e+00  9.00000e+00  1.33350e+02
          nan  4.00000e+00          nan  2.00000e+00          nan
  2.05100e+01  1.13300e+01  5.99100e+01  1.00000e+00  2.29700e+01
 -1.20000e+01          nan          nan  3.40000e+01  1.49200e+01]
[ 19.17  17.86   9.21  54.      nan  20.     6.    11.56    nan   5.85
  13.    10.91   8.     3.81 373.68  11.38  33.67   0.58    nan    nan]


In [90]:
#43
valid_hours = hours[~np.isnan(hours)]

print("25th percentile:", np.percentile(valid_hours, 25))
print("50th percentile:", np.percentile(valid_hours, 50))
print("75th percentile:", np.percentile(valid_hours, 75))

25th percentile: 4.35
50th percentile: 13.1
75th percentile: 29.49


In [92]:
#44
print(np.cumsum(hours[:20]))

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan]


In [93]:
#45
print(np.diff(hours[:20]))

[    nan    5.66   27.63  -21.87    2.54     nan     nan   -7.34     nan
     nan     nan   10.19   60.68  -44.31  -17.84   -9.57    6.41  246.85
 -249.65]


In [94]:
#46
clipped_hours = np.clip(hours, 0, 100)

print(clipped_hours)

[  nan  1.34  7.   ... 47.    2.     nan]


In [95]:
#47
whole_hours = hours.astype(int)

print(whole_hours)

[-9223372036854775808                    1                    7 ...
                   47                    2 -9223372036854775808]


/tmp/ipykernel_1285/3709725978.py:2: RuntimeWarning: invalid value encountered in cast
  whole_hours = hours.astype(int)


In [96]:
#48
hours_copy = hours.copy()

hours_copy[0] = 9999

print("Original:", hours[0])
print("Copy:", hours_copy[0])

Original: nan
Copy: 9999.0


In [97]:
#49
np.save("hours_array.npy", hours)

In [98]:
#50
billing_rate = df["billing_rate_(usd)"].to_numpy()

total_revenue = np.dot(
    np.nan_to_num(hours, nan=0),
    np.nan_to_num(billing_rate, nan=0)
)

print("Total Revenue:", total_revenue)

Total Revenue: 102879907.67480001
